# serverless.yml
org: ${env:SERVERLESS_ORG, ''}
app: ${env:SERVERLESS_APP, ''}
service: ${env:SERVERLESS_SERVICE, 'telegram-forwarder-bot'}

frameworkVersion: '4'

# Define variables section to centralize configuration
custom:
    tableName: ${env:TABLE_NAME, '${self:service}-table'}

provider:
    name: aws
    runtime: nodejs22.x
    architecture: arm64
    environment:
        BOT_TOKEN: ${env:BOT_TOKEN}
        SECRET_TOKEN: ${env:SECRET_TOKEN, ''}
        TABLE_NAME: ${self:custom.tableName}
    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                      - dynamodb:Query
                      - dynamodb:Scan
                      - dynamodb:GetItem
                      - dynamodb:PutItem
                      - dynamodb:UpdateItem
                      - dynamodb:DeleteItem
                  Resource:
                      - !GetAtt ThreadsTable.Arn
                      - !Join ['', [!GetAtt ThreadsTable.Arn, '/index/*']]

functions:
    webhook:
        handler: dist/webhook.handler
        events:
            - httpApi:
                  path: /{token}
                  method: post

resources:
    Resources:
        ThreadsTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.tableName}
                BillingMode: PAY_PER_REQUEST
                AttributeDefinitions:
                    - AttributeName: userId
                      AttributeType: S
                    - AttributeName: threadId
                      AttributeType: S
                KeySchema:
                    - AttributeName: userId
                      KeyType: HASH
                GlobalSecondaryIndexes:
                    - IndexName: ThreadIdIndex
                      KeySchema:
                          - AttributeName: threadId
                            KeyType: HASH
                      Projection:
                          ProjectionType: ALL
